import { admin, audit, edgeHandler } from "./core.ts";

type Actor={id:string;role:"admin"|"staff"|"user"};
const entriesFrom=(value:unknown)=>{if(!Array.isArray(value)||!value.length||value.length>500)throw new Error("INVALID_ENTRIES");return value.map((item)=>{const row=item as Record<string,unknown>;const number=String(row.number||"");const amount=Number(row.amount);if(!/^\d{3}$/.test(number)||!Number.isFinite(amount)||amount<=0)throw new Error("INVALID_ENTRIES");return{number,amount,has_r:Boolean(row.hasR??row.has_r)};});};

export async function saveBatch(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const entries=entriesFrom(body.entries);const {data,error}=await admin.rpc("save_batch_atomic",{p_batch_id:body.batch_id||null,p_week_id:String(body.week_id),p_user_id:String(body.user_id),p_entries:entries,p_actor_id:actor.id});if(error)throw error;return{batch:data};},["admin","staff","user"])}
export async function confirmDealer(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const {data,error}=await admin.rpc("confirm_dealer_atomic",{p_batch_id:String(body.batch_id),p_actor_id:actor.id});if(error)throw error;return{batch:data};},["admin","staff"])}
export async function approveBatch(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const {data,error}=await admin.rpc("approve_batch_atomic",{p_batch_id:String(body.batch_id),p_actor_id:actor.id});if(error)throw error;return{batch:data};},["admin"])}
export async function rejectBatch(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const {data,error}=await admin.rpc("reject_batch_atomic",{p_batch_id:String(body.batch_id),p_actor_id:actor.id,p_reason:String(body.reason||"").slice(0,200)});if(error)throw error;return{batch:data};},["admin"])}
export async function publishResult(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const number=String(body.result_number||"");if(!/^\d{3}$/.test(number))throw new Error("INVALID_RESULT");const{data,error}=await admin.rpc("publish_result_atomic",{p_week_id:String(body.week_id),p_result:number,p_actor_id:actor.id});if(error)throw error;return{result:data};},["admin"])}
export async function saveResultDraft(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const number=String(body.result_number||"");if(!/^\d{3}$/.test(number))throw new Error("INVALID_RESULT");const{data,error}=await admin.rpc("save_result_draft_atomic",{p_week_id:String(body.week_id),p_result:number,p_actor_id:actor.id});if(error)throw error;return{week:data};},["admin"])}
export async function manageClosed(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const number=String(body.number||"");if(!/^\d{3}$/.test(number))throw new Error("INVALID_NUMBER");if(body.action==="close"){const{error}=await admin.from("closed_numbers").upsert({week_id:String(body.week_id),number,reason:String(body.reason||"").slice(0,200),created_by:actor.id},{onConflict:"week_id,number"});if(error)throw error;await audit(admin,actor.id,"NUMBER_CLOSED","lottery_week",String(body.week_id),{number});}else if(body.action==="reopen"){await admin.from("closed_numbers").delete().eq("week_id",String(body.week_id)).eq("number",number);await audit(admin,actor.id,"NUMBER_REOPENED","lottery_week",String(body.week_id),{number});}else throw new Error("INVALID_ACTION");return{ok:true};},["admin"])}
export async function manageDream(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const action=String(body.action||"");if(action==="delete"){await admin.from("dream100_items").update({is_active:false}).eq("id",String(body.id));}else{const item={title_mm:String(body.title_mm||"").trim().slice(0,100),title_en:body.title_en?String(body.title_en).trim().slice(0,100):null,keywords:Array.isArray(body.keywords)?body.keywords.map(String).slice(0,30):[],numbers:Array.isArray(body.numbers)?body.numbers.map(String).filter(n=>/^\d{1,3}$/.test(n)).slice(0,10):[],emoji:String(body.emoji||"🌙").slice(0,8),short_description:String(body.short_description||"").slice(0,500),category:String(body.category||"").slice(0,50),is_active:true,created_by:actor.id};if(!item.title_mm)throw new Error("INVALID_ITEM");const query=body.id?admin.from("dream100_items").update(item).eq("id",String(body.id)):admin.from("dream100_items").insert(item);const{error}=await query;if(error)throw error;}await audit(admin,actor.id,"DREAM100_MANAGED","dream100_item",body.id?String(body.id):undefined,{action});return{ok:true};},["admin"])}
export async function manageWeek(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const action=String(body.action||"");if(action==="create"){if(body.is_current)await admin.from("lottery_weeks").update({is_current:false}).eq("is_current",true);const{data,error}=await admin.from("lottery_weeks").insert({title:String(body.title||"").trim().slice(0,100),draw_date:body.draw_date||null,is_current:Boolean(body.is_current),created_by:actor.id}).select().single();if(error)throw error;await audit(admin,actor.id,"WEEK_CREATED","lottery_week",data.id);return{week:data};}if(action==="update"){if(body.is_current)await admin.from("lottery_weeks").update({is_current:false}).neq("id",String(body.id));const allowed={title:String(body.title||"").trim().slice(0,100),draw_date:body.draw_date||null,is_open:Boolean(body.is_open),is_current:Boolean(body.is_current)};const{data,error}=await admin.from("lottery_weeks").update(allowed).eq("id",String(body.id)).select().single();if(error)throw error;await audit(admin,actor.id,"WEEK_UPDATED","lottery_week",String(body.id));return{week:data};}throw new Error("INVALID_ACTION");},["admin"])}
export async function manageUser(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const userId=String(body.user_id||"");const action=String(body.action||"");if(userId===actor.id&&action==="disable")throw new Error("INVALID_ACTION");const{data:target}=await admin.from("profiles").select("role,is_active").eq("id",userId).single();if(!target||target.role==="admin")throw new Error("PROTECTED_ACCOUNT");if(action==="enable"||action==="disable"){const active=action==="enable";await admin.from("profiles").update({is_active:active}).eq("id",userId);if(!active)await admin.auth.admin.signOut(userId,"global");await audit(admin,actor.id,active?"USER_ENABLED":"USER_DISABLED","profile",userId);return{ok:true};}if(action==="set_role"){const role=String(body.role);if(!["staff","user"].includes(role))throw new Error("INVALID_ROLE");await admin.from("profiles").update({role}).eq("id",userId);await audit(admin,actor.id,"ROLE_CHANGED","profile",userId,{old_role:target.role,new_role:role});return{ok:true};}throw new Error("INVALID_ACTION");},["admin"])}
export async function manageEntry(req:Request){return edgeHandler(req,async(body)=>{const actor=body.__actor as Actor;const entryId=String(body.entry_id||"");if(body.action!=="delete"||!/^[0-9a-f-]{36}$/i.test(entryId))throw new Error("INVALID_ACTION");const{data:entry,error:readError}=await admin.from("lottery_entries").select("id,batch_id").eq("id",entryId).single();if(readError||!entry)throw new Error("ENTRY_NOT_FOUND");const{error}=await admin.from("lottery_entries").delete().eq("id",entryId);if(error)throw error;const{count}=await admin.from("lottery_entries").select("id",{count:"exact",head:true}).eq("batch_id",entry.batch_id);if((count||0)===0)await admin.from("lottery_batches").delete().eq("id",entry.batch_id);await audit(admin,actor.id,"ENTRY_DELETED","lottery_entry",entryId);return{ok:true};},["admin","staff"])}
