import { useEffect, useState } from "react";
import { Ban, CalendarPlus, CheckCircle2, Database, ShieldCheck, Sparkles, Users } from "lucide-react";
import { PageHeading } from "../components/AppShell";
import { avatarEmoji } from "../lib/avatar";
import { invoke, safeMessage, supabase } from "../lib/supabase";
import type { LotteryBatch, LotteryWeek, Profile } from "../types";

export function AdminPage(){
  const [users,setUsers]=useState<Profile[]>([]);const [weeks,setWeeks]=useState<LotteryWeek[]>([]);const [pending,setPending]=useState<LotteryBatch[]>([]);const [tab,setTab]=useState("overview");const [message,setMessage]=useState("");const [search,setSearch]=useState("");
  const load=async()=>{const [{data:u},{data:w},{data:b}]=await Promise.all([supabase.from("profiles").select("*").order("created_at",{ascending:false}),supabase.from("lottery_weeks").select("*").order("draw_date",{ascending:false}),supabase.from("lottery_batches").select("*, profiles(nickname,avatar_key), lottery_weeks(title)").in("status",["pending","sent_to_dealer"]).order("updated_at",{ascending:false})]);setUsers((u||[])as Profile[]);setWeeks((w||[])as LotteryWeek[]);setPending((b||[])as LotteryBatch[]);};useEffect(()=>{void load();},[]);
  const action=async(name:string,body:Record<string,unknown>)=>{try{await invoke(name,body);setMessage("လုပ်ဆောင်မှု အောင်မြင်ပါသည် ✅");await load();}catch(e){setMessage(safeMessage(e));}};
  const createWeek=async()=>{const title=window.prompt("Week title", "August 16 Week");if(!title)return;const draw=window.prompt("Draw date (YYYY-MM-DD)",new Date().toISOString().slice(0,10));await action("manage-lottery-week",{action:"create",title,draw_date:draw,is_current:true});};
  const publish=async()=>{const current=weeks.find(w=>w.is_current)||weeks[0];if(!current)return setMessage("Week မရှိသေးပါ။");const number=window.prompt(`${current.title} result (3 digits)`);if(number)await action("publish-result",{week_id:current.id,result_number:number});};
  const closeNumber=async()=>{const current=weeks.find(w=>w.is_current)||weeks[0];if(!current)return;const number=window.prompt("ပိတ်မည့် 3-digit number");if(number)await action("manage-closed-number",{action:"close",week_id:current.id,number});};
  return <><PageHeading eyebrow="CONTROL CENTER" title="Admin Panel" description="Users, weeks, approvals နှင့် result publishing ကို စီမံပါ။"/>
    <div className="admin-tabs">{[["overview","Overview"],["users","Members"],["approvals","Approvals"],["audit","Audit"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>{message&&<div className={message.includes("အောင်မြင်")?"success-note":"form-error"}>{message}</div>}
    {tab==="overview"&&<><div className="admin-metrics"><div><span><Users/></span><b>{users.length}</b><small>Total members</small></div><div><span><CalendarPlus/></span><b>{weeks.length}</b><small>Lottery weeks</small></div><div><span><ShieldCheck/></span><b>{pending.length}</b><small>Need attention</small></div><div><span><Database/></span><b>{users.filter(u=>u.is_active).length}</b><small>Active accounts</small></div></div><section className="quick-actions card"><h2>Quick Actions</h2><div><button onClick={()=>void createWeek()}><CalendarPlus/>Create Week</button><button onClick={()=>void publish()}><Sparkles/>Publish Result</button><button onClick={()=>void closeNumber()}><Ban/>Close Number</button></div></section></>}
    {tab==="users"&&<section className="admin-table card"><header><h2>Member Records</h2><input placeholder="Search nickname or Generated ID" value={search} maxLength={40} onChange={e=>setSearch(e.target.value)}/></header>{users.filter(user=>`${user.nickname||""} ${user.generated_name}`.normalize("NFC").toLocaleLowerCase().includes(search.normalize("NFC").toLocaleLowerCase())).map(user=><div className="table-row" key={user.id}><span className="avatar small">{avatarEmoji(user.avatar_key)}</span><div><b>{user.nickname||"No nickname"}</b><code>{user.generated_name}</code></div><span className="role-tag">{user.role}</span><button className="secondary" onClick={()=>void action("manage-user",{user_id:user.id,action:user.is_active?"disable":"enable"})}>{user.is_active?"Deactivate":"Activate"}</button></div>)}</section>}
    {tab==="approvals"&&<section className="admin-table card"><header><h2>Pending Approval</h2></header>{!pending.length?<p className="muted padded">စောင့်ဆိုင်းနေသော batch မရှိပါ။</p>:pending.map(batch=><div className="table-row" key={batch.id}><span className="avatar small">{avatarEmoji(batch.profiles?.avatar_key)}</span><div><b>{batch.profiles?.nickname}</b><small>{batch.lottery_weeks?.title}</small></div><strong>{Number(batch.total_amount).toLocaleString()} Ks</strong><button className="primary" onClick={()=>void action("approve-lottery-batch",{batch_id:batch.id})}><CheckCircle2/>Approve</button></div>)}</section>}
    {tab==="audit"&&<AuditList/>}</>;
}
function AuditList(){const [items,setItems]=useState<{id:number;action:string;entity_type:string;created_at:string;metadata:Record<string,string>}[]>([]);useEffect(()=>{void supabase.from("audit_logs").select("id,action,entity_type,created_at,metadata").order("created_at",{ascending:false}).limit(50).then(({data})=>setItems(data||[]));},[]);return <section className="audit-list card"><h2>Audit Timeline</h2>{items.map(item=><div key={item.id}><i/><div><b>{item.action}</b><p>{item.entity_type||"system"}</p></div><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</section>}
