import { useEffect, useMemo, useState } from "react";
import { Check, Clipboard, Copy, Plus, Save, Send, UserPlus } from "lucide-react";
import { PageHeading } from "../components/AppShell";
import { useAuth } from "../auth/AuthProvider";
import { avatarEmoji } from "../lib/avatar";
import { parseEntryText } from "../lib/lottery";
import { invoke, safeMessage, supabase } from "../lib/supabase";
import type { LotteryBatch, LotteryWeek, Profile } from "../types";

interface CreatedCredentials { generated_name: string; one_time_code: string; expires_at: string }
export function EntryPage() {
  const { profile: operator } = useAuth();
  const [weeks,setWeeks]=useState<LotteryWeek[]>([]); const [members,setMembers]=useState<Profile[]>([]); const [weekId,setWeek]=useState(""); const [userId,setUser]=useState(""); const [text,setText]=useState(""); const [batch,setBatch]=useState<LotteryBatch|null>(null); const [message,setMessage]=useState(""); const [createOpen,setCreateOpen]=useState(false); const [credentials,setCredentials]=useState<CreatedCredentials|null>(null); const [copyOptions,setCopyOptions]=useState({sequence:true,nickname:true,total:true,closed:true});
  const load = async () => { const [{data:w},{data:m}] = await Promise.all([supabase.from("lottery_weeks").select("*").order("draw_date",{ascending:false}),supabase.from("profiles").select("*").eq("role","user").eq("is_active",true).order("created_at")]); const weekList=(w||[]) as LotteryWeek[]; const memberList=(m||[]) as Profile[]; setWeeks(weekList); setMembers(memberList); setWeek((v)=>v||weekList.find(x=>x.is_current)?.id||weekList[0]?.id||""); setUser((v)=>v||memberList[0]?.id||""); };
  const loadBatch = async () => { if(!weekId||!userId){setBatch(null);return;} const {data}=await supabase.from("lottery_batches").select("*, lottery_entries(*)").eq("week_id",weekId).eq("user_id",userId).order("created_at",{ascending:false}).limit(1).maybeSingle(); setBatch(data as LotteryBatch|null); if(data?.lottery_entries) setText((data.lottery_entries as {number:string;amount:number}[]).map(e=>`${e.number}-${e.amount}`).join("\n")); else setText(""); };
  useEffect(()=>{void load();},[]); useEffect(()=>{void loadBatch();},[weekId,userId]);
  const selected=members.find(m=>m.id===userId); const parsed=useMemo(()=>{try{return parseEntryText(text);}catch{return[];}},[text]); const total=parsed.reduce((n,e)=>n+e.amount+(e.reverseAmount||0),0);
  const save = async () => { setMessage(""); try { const entries=parseEntryText(text); await invoke(batch?"update-lottery-batch":"create-lottery-batch",{batch_id:batch?.id,week_id:weekId,user_id:userId,entries}); setMessage("ဂဏန်းစာရင်း သိမ်းပြီးပါပြီ ✅"); await loadBatch(); } catch(e){setMessage(safeMessage(e));} };
  const transition = async (name:string) => { if(!batch)return; try{await invoke(name,{batch_id:batch.id});setMessage(name==="submit-to-dealer"?"ဒိုင်သို့ ပို့ပြီးဖြစ်ကြောင်း မှတ်တမ်းတင်ပြီးပါပြီ။":"Batch အတည်ပြုပြီးပါပြီ 🎉");await loadBatch();}catch(e){setMessage(safeMessage(e));} };
  const copyAll = async () => { const sequence=copyOptions.sequence?`(${batch?.sequence_no||"—"})`:""; const name=copyOptions.nickname?` ${selected?.nickname||"EZWin Member"}`:""; const lines=parsed.map(e=>`${e.number}-${e.amount}${copyOptions.closed&&batch?.lottery_entries?.find(x=>x.number===e.number)?.is_closed?" (X ပိတ်)":""}`).join("\n"); const footer=copyOptions.total?`\n\nTotal - ${total.toLocaleString()} Ks`:""; await navigator.clipboard.writeText(`${sequence}${name}\n\n${lines}${footer}`.trim());setMessage("Copy လုပ်ပြီးပါပြီ 📋"); };
  return <><PageHeading eyebrow="OPERATIONS" title="ဂဏန်းထည့်မည်" description="Member တစ်ဦးချင်းအတွက် အပတ်စဉ်ဂဏန်းများကို စီမံပါ။" action={<button className="primary" onClick={()=>setCreateOpen(true)}><UserPlus/> Create User</button>}/>
    <section className="entry-toolbar card"><label>Week<select value={weekId} onChange={e=>setWeek(e.target.value)}>{weeks.map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label><label>Member<select value={userId} onChange={e=>setUser(e.target.value)}>{members.map((m,i)=><option key={m.id} value={m.id}>({i+1}) {m.nickname||m.generated_name}</option>)}</select></label><button className="secondary" onClick={()=>setCreateOpen(true)}><Plus/> New member</button></section>
    {selected&&<section className="selected-member"><span className="avatar">{avatarEmoji(selected.avatar_key)}</span><div><small>SELECTED MEMBER</small><b>{selected.nickname||"Nickname မရှိသေးပါ"}</b><code>{selected.generated_name}</code></div></section>}
    <div className="entry-grid"><section className="card"><div className="card-title"><div><p className="eyebrow">MULTILINE INPUT</p><h2>ဂဏန်းစာရင်း</h2></div><Clipboard/></div><textarea className="entry-textarea" value={text} onChange={e=>setText(e.target.value)} placeholder={"455-2000\n555-2000\n422-500"}/><p className="field-help">3-digit number + amount · 145R-5000 နှင့် 145-5000R500 ကိုလည်း လက်ခံသည်</p><div className="entry-summary"><span>{parsed.length} lines</span><b>Total · {total.toLocaleString()} Ks</b></div><button className="primary wide" onClick={()=>void save()}><Save/> Save List</button></section>
      <section className="card copy-panel"><div className="card-title"><div><p className="eyebrow">DEALER FORMAT</p><h2>Copy All</h2></div><Copy/></div>{Object.entries({sequence:"Member Sequence",nickname:"Nickname",total:"Total",closed:"Closed Number Marker"}).map(([key,label])=><label className="check-row" key={key}><input type="checkbox" checked={copyOptions[key as keyof typeof copyOptions]} onChange={e=>setCopyOptions({...copyOptions,[key]:e.target.checked})}/><span><Check/>{label}</span></label>)}<button className="secondary wide" onClick={()=>void copyAll()}><Copy/> Copy All</button>{batch&&<div className="workflow-actions"><button onClick={()=>void transition("submit-to-dealer")}><Send/> ဒိုင်သို့ပို့ပြီး</button>{operator?.role==="admin"&&<button onClick={()=>void transition("approve-lottery-batch")} disabled={!batch.dealer_confirmed_at}><Check/> Approve</button>}</div>}</section></div>
    {message&&<div className={message.includes("ပြီး")?"success-note":"form-error"}>{message}</div>}
    {createOpen&&<CreateUserModal credentials={credentials} setCredentials={setCredentials} onClose={()=>{setCreateOpen(false);setCredentials(null);void load();}}/>}</>;
}

function CreateUserModal({credentials,setCredentials,onClose}:{credentials:CreatedCredentials|null;setCredentials:(v:CreatedCredentials|null)=>void;onClose:()=>void}){
  const [nickname,setNickname]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const create=async()=>{setBusy(true);setMessage("");try{setCredentials(await invoke<CreatedCredentials>("create-ezwin-user",{nickname:nickname.trim()||null}));}catch(e){setMessage(safeMessage(e));}finally{setBusy(false);}};
  const copy=()=>credentials&&navigator.clipboard.writeText(`Generated ID: ${credentials.generated_name}\nOne-Time Code: ${credentials.one_time_code}`);
  return <div className="modal-backdrop"><div className="modal credential-modal"><button className="modal-close" onClick={onClose}>×</button>{credentials?<><div className="success-orb">✓</div><p className="eyebrow">USER CREATED SUCCESSFULLY</p><h2>User Created</h2><div className="credential-box"><small>Generated ID</small><strong>{credentials.generated_name}</strong><small>One-Time Code</small><strong>{credentials.one_time_code}</strong></div><div className="warning-note">⚠️ ဒီ code ကို တစ်ကြိမ်သာ ပြသပါမည်။ ပိတ်ပြီးနောက် ပြန်ကြည့်၍ မရပါ။</div><button className="primary wide" onClick={()=>void copy()}><Copy/> Copy Credentials</button><button className="text-button wide" onClick={onClose}>Done</button></>:<><div className="auth-icon"><UserPlus/></div><p className="eyebrow">NEW EZWIN MEMBER</p><h2>Create User</h2><p>Permanent Generated ID နှင့် သက်တမ်းရှိ One-Time Code ကို server က လုံခြုံစွာ ဖန်တီးပါမည်။</p><label>Nickname (optional)<input value={nickname} maxLength={30} onChange={e=>setNickname(e.target.value)} placeholder="ဆရာကြီး"/></label>{message&&<div className="form-error">{message}</div>}<button className="primary wide" disabled={busy} onClick={()=>void create()}>{busy?"ဖန်တီးနေပါသည်...":"Create User"}</button></>}</div></div>;
}
